[package]
name = "umls"
version = "0.1.0"
edition = "2021"

[dependencies]
hex-literal = "0.4.1"
hybrid-array = "0.2.3"
derive-view = { path = "derive-view" }

[features]
x25519_aes128gcm_ed25519 = []
default = ["x25519_aes128gcm_ed25519"]
