[package]
name = "hactar-platform-macos"
version = "0.1.0"
edition = "2021"

[dependencies]
hactar-platform = { version = "0.1.0", path = "../hactar-platform" }
tokio = { version = "1.41.0", features = ["full"] }
