[package]
name = "spike"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
cpal = "0.15.3"
itertools = "0.13.0"
ringbuf = "0.4.7"

[build-dependencies]
cc = "1.2.3"
