[package]
name = "ui_rs"
version = "0.1.0"
edition = "2021"

[build]
rustflags = ["-Cpanic=abort"]

[dependencies]
cortex-m-rt = "0.7.5"
stm32f4xx-hal = { version = "0.22.1", features = ["stm32f405"] }

[build-dependencies]
cc = { version = "1.2.3", features = ["parallel"] }
