

name: Copy nightly mgmt binary to github pages
inputs:
  github_token:
    required: true
    default: ''
runs:
  using: "composite"
  steps:
  - name: Checkout gh-pages branch
    uses: actions/checkout@v4
    with:
      ref: gh-pages
  - name: Download mgmt bin
    shell: bash
    run: |
      mkdir -p build/mgmt
      gh release download nightly -p 'mgmt.bin' -D build/mgmt
    env:
      GITHUB_TOKEN: ${{ inputs.github_token }}
  - name: Commit and push mgmt binary
    shell: bash
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "github-actions[bot]@users.noreply.github.com"
      git add build
      git commit -m "Update mgmt binary from Nightly build" || echo "No changes to commit"
      git push origin gh-pages