name: Upload Firmware Assets CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: [ "Build Firmware CI" ]
    types:
      - completed

jobs:
  upload:
    runs-on:  ubuntu-latest
    needs: [build-mgmt, build-ui, build-net]
    steps:
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          files: |
            firmware/mgmt/build/mgmt.bin
            firmware/net/build/bootloader/bootloader.bin
            firmware/net/build/partition_table/partition-table.bin
            firmware/net/build/net.bin
            firmware/net/build/net.elf
            firmware/ui/build/ui.bin