name: Upload Binaries
on:
  workflow_run:
    workflows: [Build Firmware CI]
    types: [completed]
    branches: [main, copy_binaries]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Download mgmt bin
        shell: bash
        run: |
          mkdir -p build/mgmt
          gh release download nightly -p 'mgmt.bin' -D build/mgmt --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push mgmt binary
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add build
          git commit -m "Update mgmt binary from Nightly build" || echo "No changes to commit"
          git push origin gh-pages
